package com.nice.entity;

import java.io.Serializable;
import java.util.Date;

/**
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table activation_code
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class ActivationCode implements Serializable {
    /**
     * Database Column Remarks:
     * id
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activation_code.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     * Database Column Remarks:
     * 激活码
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activation_code.activation_code
     *
     * @mbg.generated
     */
    private String activationCode;

    /**
     * Database Column Remarks:
     * 是否使用
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activation_code.is_activated
     *
     * @mbg.generated
     */
    private Integer state;

    /**
     * Database Column Remarks:
     * 激活时间
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activation_code.start_time
     *
     * @mbg.generated
     */
    private Long startTime;

    /**
     * Database Column Remarks:
     * 到期时间
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activation_code.end_time
     *
     * @mbg.generated
     */
    private Long endTime;

    /**
     * Database Column Remarks:
     * 设备码
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activation_code.installation_code
     *
     * @mbg.generated
     */
    private String installationCode;

    /**
     * Database Column Remarks:
     * 设备信息
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activation_code.device_info
     *
     * @mbg.generated
     */
    private String deviceInfo;

    /**
     * Database Column Remarks:
     * 类型
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activation_code.type
     *
     * @mbg.generated
     */
    private Integer type;

    /**
     * Database Column Remarks:
     * 备注
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activation_code.remark
     *
     * @mbg.generated
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table activation_code
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activation_code.id
     *
     * @return the value of activation_code.id
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activation_code.id
     *
     * @param id the value for activation_code.id
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activation_code.activation_code
     *
     * @return the value of activation_code.activation_code
     * @mbg.generated
     */
    public String getActivationCode() {
        return activationCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activation_code.activation_code
     *
     * @param activationCode the value for activation_code.activation_code
     * @mbg.generated
     */
    public void setActivationCode(String activationCode) {
        this.activationCode = activationCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activation_code.is_activated
     *
     * @return the value of activation_code.is_activated
     * @mbg.generated
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activation_code.is_activated
     *
     * @param state the value for activation_code.is_activated
     * @mbg.generated
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activation_code.start_time
     *
     * @return the value of activation_code.start_time
     * @mbg.generated
     */
    public Long getStartTime() {
        return startTime;
    }

    public void setStartTime(Long startTime) {
        this.startTime = startTime;
    }

    public Long getEndTime() {
        return endTime;
    }

    public void setEndTime(Long endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activation_code.installation_code
     *
     * @return the value of activation_code.installation_code
     * @mbg.generated
     */
    public String getInstallationCode() {
        return installationCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activation_code.installation_code
     *
     * @param installationCode the value for activation_code.installation_code
     * @mbg.generated
     */
    public void setInstallationCode(String installationCode) {
        this.installationCode = installationCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activation_code.device_info
     *
     * @return the value of activation_code.device_info
     * @mbg.generated
     */
    public String getDeviceInfo() {
        return deviceInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activation_code.device_info
     *
     * @param deviceInfo the value for activation_code.device_info
     * @mbg.generated
     */
    public void setDeviceInfo(String deviceInfo) {
        this.deviceInfo = deviceInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activation_code.type
     *
     * @return the value of activation_code.type
     * @mbg.generated
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activation_code.type
     *
     * @param type the value for activation_code.type
     * @mbg.generated
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activation_code.remark
     *
     * @return the value of activation_code.remark
     * @mbg.generated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activation_code.remark
     *
     * @param remark the value for activation_code.remark
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }
}