package com.nice.entity;

import java.io.Serializable;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table tt_view_id
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class ViewId implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tt_view_id.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tt_view_id.click_info
     *
     * @mbg.generated
     */
    private String clickInfo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tt_view_id.view_id
     *
     * @mbg.generated
     */
    private String viewId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tt_view_id.version
     *
     * @mbg.generated
     */
    private String version;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tt_view_id.time
     *
     * @mbg.generated
     */
    private Date time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tt_view_id
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tt_view_id.id
     *
     * @return the value of tt_view_id.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tt_view_id.id
     *
     * @param id the value for tt_view_id.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tt_view_id.click_info
     *
     * @return the value of tt_view_id.click_info
     *
     * @mbg.generated
     */
    public String getClickInfo() {
        return clickInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tt_view_id.click_info
     *
     * @param clickInfo the value for tt_view_id.click_info
     *
     * @mbg.generated
     */
    public void setClickInfo(String clickInfo) {
        this.clickInfo = clickInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tt_view_id.view_id
     *
     * @return the value of tt_view_id.view_id
     *
     * @mbg.generated
     */
    public String getViewId() {
        return viewId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tt_view_id.view_id
     *
     * @param viewId the value for tt_view_id.view_id
     *
     * @mbg.generated
     */
    public void setViewId(String viewId) {
        this.viewId = viewId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tt_view_id.version
     *
     * @return the value of tt_view_id.version
     *
     * @mbg.generated
     */
    public String getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tt_view_id.version
     *
     * @param version the value for tt_view_id.version
     *
     * @mbg.generated
     */
    public void setVersion(String version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tt_view_id.time
     *
     * @return the value of tt_view_id.time
     *
     * @mbg.generated
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tt_view_id.time
     *
     * @param time the value for tt_view_id.time
     *
     * @mbg.generated
     */
    public void setTime(Date time) {
        this.time = time;
    }
}